### ISSUE TITLE
Release of v0.0.1

### ISSUE THREAD

**Issue by c-moeller** [oemof/oemof-thermal#23]
We set a milestone for the first release of oemof-thermal by December 24th.

@oemof/oemof-heat Let's use this issue to discuss what need to be done to achieve this.

**Comment by jnnr** [comment]
Thanks for bringing this up. The release should contain the components that are in review at the moment.

#7
#16
#19
#20
#21
#22

What is the status of #7?

For the actual release process, we can consult https://github.com/oemof/oemof/wiki/How-to-release

**Comment by uvchik** [comment]
> December 24th

:joy: :santa: :christmas_tree:

**Comment by jnnr** [comment]
I adapted the date for the release to a more realistic one (16/12/2019). Still, we can regard it as a christmas present to ourselves :)

To be able to present the new features at the upcoming dev meeting, we aim to finish reviews and merge into dev until 04/12/2019.

**Comment by c-moeller** [comment]
* [x] Remove png files from CSP and flat plate collector example
* [x] Remove lp file from stratified storage example
* [x] Correct plot in CSP example (there is an empty plot)

**Comment by jnnr** [comment]
* [x] install_requires are not installed
* [x] Example overview lacks flat plate collector
* [x] inconsistant naming: Example is called flat plate collector, module solar thermal collector

**Comment by c-moeller** [comment]
What does the footnote "1" mean in the examples doc?

**Comment by FranziPl** [comment]
> 
> 
> What does the footnote "1" mean in the examples doc?

[1] Example uses *oemof.solph*


(I have no idea, why it is build in this strange way)

**Comment by jnnr** [comment]
> (I have no idea, why it is build in this strange way)

The numbers 1,2,3,4,5 are the links back from where the footnote came.  Might be useful for a large document. In this case this feature is rather confusing.

**Comment by c-moeller** [comment]
We are now just before merging the release branch into the master branch. I will start with this tomorrow and complete the release.

**Comment by c-moeller** [comment]
oemof.thermal is now on Pypi and the release (almost) completed:
https://pypi.org/project/oemof.thermal/0.0.1/

Does anyone know if the documentation is built automatically? Till now there is no v0.0.1 at readthedocs: https://oemof-thermal.readthedocs.io/en/latest/

There are some few points I would like to do in the beginning of January:
* [x] Wordpress news post --> I would like to do that in the new year to avoid that the news disappear due to christmas holidays
* [x] Edit Whatnew file --> together with the news post
* [x] Adapt Zenodo entry --> Do we need this? I have no idea what to do here....

**Comment by jnnr** [comment]
Hey, thanks again for the great work and the all little and big efforts to make the first release happen! 
:) Only a few things missing before it is complete.

> Does anyone know if the documentation is built automatically? Till now there is no v0.0.1 at readthedocs: https://oemof-thermal.readthedocs.io/en/latest/

Yes, that works. If you select 'stable' ~~'master'~~, you get the v0.0.1 version of the docs. 'Latest' corresponds to the dev branch.

>     * [ ]  Edit Whatnew file --> together with the news post

There is a what's new file present, which just tells that this is the first release. It might be unusual to update that after we already released. A release should be fixed once it is out. In my view, the short description for this first version is ok. In future releases, the description should be more extended, because it tells users how the package changed compared to a previous version already known to them. Conclusion: I do not see that we have to do this, thus I checked the box.

>     * [ ]  Adapt Zenodo entry --> Do we need this? I have no idea what to do here....

Most of oemof's libraries have a zenodo entry (have a look here if you like https://zenodo.org/search?page=1&size=20&q=oemof). You need a zenodo account to upload it.

**Comment by jnnr** [comment]
I logged into zenodo and added oemof.thermal. It suggests me to create a first release, but I cannot make it recognize the existing v0.0.1 release. I will give an update as soon as I know more.

**Comment by jnnr** [comment]
I could resolve the problem by checking out the release, creating a new branch, removing the release tag locally and on the remote. Then I could reassign the release to the newly created branch. This triggered zenodo, so we have a zenodo entry now. Thanks to uvchik!

**Comment by jnnr** [comment]
Thereby, the release is completed and I will close the issue.
