### ISSUE TITLE
Missing example of emission allocation with solph

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#80]
@jakob-wo 

- [ ] Add example with solph.

**Comment by jakob-wo** [comment]
I was thinking about possible examples. But I do not find a realistic application. 

Using the emission allocation with solph would make sense if I had a district heating demand that I would cover with a CHP and minimize the CO2-Emissions of the object that creats the demand (using emissions for _variable_costs_) with no regard to the emissions that are linked to the electricity feed-in while heat is produced (--> no system-wide emission minimization).
In real life (german regulatory framework) it is not the Emissions itself that count but the primary energy consumption. Therefore the district heat has to fullfil certain primary energy factor instead of a certain amount of emission.

**Comment by jnnr** [comment]
Is the primary energy factor related to the PEE in the finish method (Primärenergieeinsparung)?

**Comment by jnnr** [comment]
After discussing again, we did not come up with a simple example using solph and emission allocation together. The existing example on emission allocation is quite illustrative and should be enough to understand how it works. Therefore, I close this issue.
